### ISSUE TITLE
the  structure

### ISSUE THREAD

**Issue by fang-lg** [wufan-cse/gnas#4]
Your search phase is to determine the structure of the model's prediction head based on star energy during training. Since the search phase has already determined the model structure based on performance, why do you need to go through an enhancement phase?

**Comment by wufan-cse** [comment]
G-NAS is designed based on Differential-NAS (DARTS), which uses softmax to select operations during the search process. As shown in Figure 3 of the G-NAS paper, after the model converges (t=t), the search stage will still participate in the calculation of the final result for operations that were not selected (such as o_q). In order to transform the weight \alpha from continuous data to discrete data, we chose to add an augmentation stage in engineering to reconstruct the network, delete unselected operations, and enhance the impact of selected operations on the prediction results. Thank you.
